name: Java CI Pipeline

on:
  push:
    branches:
<<<<<<< HEAD
      - main
=======
      - master
>>>>>>> b4984851c390d46744553e8fa6be3eb6f21dc245

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compile Java Program
        run: javac Main.java

      - name: Run Java Program
        run: java Main

        -name: Run Custom Action
        uses: ./.github/actions/java-build

      
